<?php

/**
 * @link: https://tech.yandex.ru/share/
 */

/* @var $this \SN\View\Widget */

?>
<section class="sn">
    <h2><?php echo $this->getTitle() ?></h2>
<!--    <script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>-->
    <script src="//yastatic.net/share2/share.js" async="async"></script>
    <div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,gplus,twitter,linkedin,viber,telegram"></div>
</section>